name: Python Application

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run review Script
        env:
            GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
            EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
            RECEIVER_EMAILL: ${{ secrets.RECEIVER_EMAILL}}
            SENDER_EMAIL: ${{secrets.SENDER_EMAIL}}
        run: |
          python ./scripts/review.py